#!/bin/bash
echo ---------- Stopping server...
forever stop schemeappadmin.js
echo ---------- Fetching new version from repository...
git pull
echo ---------- Restarting server...
forever start schemeappadmin.js
echo ---------- Done!