#!/bin/bash
echo ---------- Stopping server...
forever stop schemeappserver.js
echo ---------- Removing old log files...
rm /home/eosterberg/.forever/*.log
echo ---------- Fetching new version from repository...
git pull
echo ---------- Restarting server...
forever start schemeappserver.js
echo ---------- Done!